require(sqldf)
tmpsql <- tmpsql <- "select * from file where Date = '2/2/2007' or Date = '1/2/2007'"
d <- read.csv2.sql("household_power_consumption.txt",tmpsql)
d$DateTime <- strptime(paste(d$Date, d$Time), format="%d/%m/%Y %H:%M:%S")
png(file="plot4.png",width=480,height=480)
par(mfrow = c(2,2))
hist(d$Global_active_power,col="Red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
plot(d$DateTime,d$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(d$DateTime,d[,7],type="l",ylab = "Energy sub metering",xlab="")
points(d$DateTime,d[,8],col='red',type='l')
points(d$DateTime,d[,9],col='blue',type='l')
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch="-")
plot(d$DateTime,d$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()